version: '3'

services:
  home-electricity:
    container_name: home-electricity 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3439:3000'
    restart: unless-stopped
    volumes:
      - ./prisma:/app/prisma